---
title: "First Knit"
author: "Kevin Ortega"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended Pete Knight High School. I did graduate thankfully. I was more of a fan of english but I graded fairly well in both. I enjoyed the reading and discussion more in english then the math problems we had to do.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
  I have a windows computer at home and a windows laptop that I use for school. I would rate myself about a 6/10 in being able to use a computer. I do have internet access at home and it is reliable enough for me to do all my school work.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   I preferred being called Kevin by my friends and family. Somtimes people call me Kev if they're feelinf adventurous. Mostly, however, Kevin is fine. 
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   I'm trying to become a dental Hygenist, and that is the reason I've returned to school. The college subject that's the most interest to me are the subjects pertaining to that major. Maybe not the not the most exciting, but it is what it is. I'm trying for a bachelors in science.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   The only foreign country I've been to is El Salvador. That's where my family is from however it's been a long time since I've gone. I haven't been there since I was 8. That said, I've always wanted to go to Japan and see the cherry blossum trees. If I had to get drafted to the military anywhere, I would choose to be in SpaceForce... because why not?
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   I'm taking Math 115. I'm taking the class to bring up my GPA because I acutally took the class a long time ago and failed... and here I am trying again for a better grade and better GPA. That's the plan and I hope this round of the class turns out better.
 






  




